### ISSUE TITLE
Roadmap 0.12.0

### ISSUE THREAD

**Issue by azu** [almin/almin#161]
## Breaking Changes

- [x] Remove `prevState` arguments from `Store#getState(prevState?)` #162
  - It not break something in our observational range
- [x] Drop `StoreGroup` and `QueuedStoreGroup` #174 
  - [almin/migration-tools: Migration scripts for Almin.](https://github.com/almin/migration-tools "almin/migration-tools: Migration scripts for Almin.")
  - use new `StoreGroup` insteadof [legacy-store-group](https://github.com/almin/legacy-store-group "legacy-store-group").
  - you need to change `Store#getState` signature.

### 💟 Migration Guide 

You can migrate almin 0.11.x to 0.12.0 by using [migration-tools](https://github.com/almin/migration-tools "almin/migration-tools: Migration scripts for Almin.")

```bash
# Installation
npm install -g jscodeshift @almin/migration-tools 
# Migrate *Store.js
## Target file path should be change
jscodeshift --run-in-band -t `npm root -g`/@almin/migration-tools/scripts/store-get-state-return-object-to-flat.js src/store/*/**/*Store.js
# Migrate old StoreGroup to new StoreGroup
## Target file path should be change
jscodeshift --run-in-band -t `npm root -g`/@almin/migration-tools/scripts/store-group-arguments.js src/store/AppStore.js
```

Actual examples:

- [chore(deps): update dependencies by azu · Pull Request #11 · azu/presentation-annotator](https://github.com/azu/presentation-annotator/pull/11 "chore(deps): update dependencies by azu · Pull Request #11 · azu/presentation-annotator")
- [chore(almin): Update to Almin 0.12 by azu · Pull Request #5 · textlint/textlint-app](https://github.com/textlint/textlint-app/pull/5 "chore(almin): Update to Almin 0.12 by azu · Pull Request #5 · textlint/textlint-app")

If you want to use legacy implemenration of StoreGroup and Store, please see [almin/legacy-store-group](https://github.com/almin/legacy-store-group "almin/legacy-store-group: Almin old StoreGroup and QueuedStoreGroup implementation.").

## Features

- [x] Replace old `StoreGroup` as new `StoreGroup`#154 #159  
  - It contains a breaking change. #159 
- [x] Add `receivePayload(payload)` to `Store` for `StoreGroup` #160 
- [x] Add `shouldStateUpdate(prevState, nextState)` to `Store` for `StoreGroup` 
   - [x] Update StoreLike interface

New usage of `StoreGroup` and `Store`

**Before**:

```js
class AStore extends Store {
    getState() {
        return {a : "a value"};
    }
}
class BStore extends Store {
    getState() {
        return {b : "b value"};
    }
}
const aStore = new AStore();
const bStore = new BStore();
const storeGroup = new StoreGroup(
    aStore,
    bStore
]);
console.log(storeGroup.getState());
// { a: "a value", b: "b value" }
```

**After**:

Almin 0.12 require following syntax.
(Store#getState and StoreGroup constructor is changed.)

```js
class AStore extends Store {
    getState() {
        return "a value";
    }
}
class BStore extends Store {
    getState() {
        return "b value";
    }
}
const aStore = new AStore();
const bStore = new BStore();
const storeGroup = new StoreGroup({
    // stateName: store
    a: aStore,
    b: bStore
});
console.log(storeGroup.getState());
// { a: "a value", b: "b value" }
```

Please see documentation.

- [Hello World · Almin.js](https://almin.js.org/docs/introduction/hello-world.html "Hello World · Almin.js")
- [Counter App · Almin.js](https://almin.js.org/docs/tutorial/counter/ "Counter App · Almin.js")
- [Todo App · Almin.js](https://almin.js.org/docs/tutorial/todomvc/ "Todo App · Almin.js")

## Documents

- [ ] Make clear `Store` position #160 #186 
- [x] Update TodoMVC tutorial

## TypeScript

- **Core**: Upgrade to TypeScript 2.3 #178 
- **Store**: Make clear the relation Store and State #165 
- **Context**: Make `Context#getState` explicit #166 
- **Context**: Make `store` arguments of constructor simple

## Internal

- Move to monorepo #182 

## Not in 0.12

- Transaction UseCase

**Comment by azu** [comment]
Side notes

- Follow https://github.com/almin/almin-react-container
- https://github.com/almin/almin-reduce-store maybe depreacted?

**Comment by azu** [comment]
#179 should be fixed in 0.12.

**Comment by azu** [comment]
We can 0.12 beta by following

```
npm i -S almin@beta
```

**Comment by azu** [comment]
Release https://github.com/almin/almin/releases/tag/almin%400.12.3
