### ISSUE TITLE
Deprecate `executor()`

### ISSUE THREAD

**Issue by azu** [almin/almin#356]
`UseCaseExecutor#executor` has been introduced as a workaround of " TypeScript: improve UseCase#execute typing #107 ".

Now(Almin 17+), `UseCaseExecutor#execute` type will be complete in #355 

The user should use `UseCaseExecutor#execute` instead of `UseCaseExecutor#executor`.

## Changes

Before:  `executor()`

```ts
import { UseCase, Context } from "almin";
class MyUseCaseA extends UseCase {
    execute(_a: string) {}
}
const context = new Context({
    store: createStore({ name: "test" })
});

// executor
context.useCase(new MyUseCaseA()).executor(useCase => useCase.execute("A")); 
```

After: `execute()`

```ts
import { UseCase, Context } from "almin";
class MyUseCaseA extends UseCase {
    execute(_a: string) {}
}
const context = new Context({
    store: createStore({ name: "test" })
});

//execute
context.useCase(new MyUseCaseA()).execute("A");
```

## Task

- [x] Deprecated `UseCaseExecutor#executor` #355 
- [x] Deprecated warning message #355 
- [ ] Migration tools for TypeScript
- [ ] Drop to support (Probably 1.0)
